// <auto-generated />
namespace MedicalJournal.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initoffice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initoffice));
        
        string IMigrationMetadata.Id
        {
            get { return "201612270741148_init-office"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
